

try{

}catch(e){
    console.log("Exception",e)
}